# Generated by Django 2.1.3 on 2018-11-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcomments',
            options={'verbose_name': 'Event Coment', 'verbose_name_plural': 'Event Coments'},
        ),
    ]
