# Generated by Django 2.1.3 on 2018-11-15 21:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('icon_perfil', models.CharField(max_length=100, verbose_name='Icon_Perfil')),
                ('category', models.CharField(max_length=15, verbose_name='Category')),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Event Coment',
                'verbose_name_plural': 'Event Coments',
                'ordering': ['-created'],
            },
        ),
    ]
